### PR TITLE
Add treasury chart

### LINKED ISSUE #48: 4th Module - Treasury Transaction Charts
No front end on Treasury all work has stopped progress was made with Migwee 
No one is working on Treasury votes

### PR DESCRIPTION
**Pull request by crux25**
Closes #48 
This PR Adds treasury charts module.

### CODE REVIEW

**Review by devchoplife — DISMISSED** [review]
Looks good to me 
Approved changes

**Review by devchoplife — COMMENTED** [review]
I am unable to build the js packages

**Comment by crux25** [comment]
> I am unable to build the js packages
Share the error message.

**Review by devchoplife — COMMENTED** [review]
Treasury transaction page throws an error when I try to navigate to it from the main navigation menu

Error image:
Screenshot from 2021-12-07 13-32-46

**Comment by crux25** [comment]
> Treasury transaction page throws an error when I try to navigate to it from the main navigation menu
> 
> Error image: Screenshot from 2021-12-07 13-32-46

This error is occurring because you're either missing  apiurl or the url is malformed. Since this error isn't localized to the treasury module, but impacts other modules that fetches data from the api url I have opened issue #60 to address it.

**Comment by devchoplife** [comment]
> > Treasury transaction page throws an error when I try to navigate to it from the main navigation menu
> > Error image: Screenshot from 2021-12-07 13-32-46
> 
> This error is occurring because you're either missing apiurl or the url is malformed. Since this error isn't localized to the treasury module, but impacts other modules that fetches data from the api url I have opened issue #60 to address it.

Added the URL manually and it works now

**Review by devchoplife — APPROVED** [review]
Looks good and works fine although there are minor issue related to other modules. Separate issues have been created to tackle these issues.
Great job

**Pull request merged**
